spring.application.name=expenses-core

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/expenses_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=your_super_secret_key_replace_this_with_a_long_random_string_256bits
app.jwt.expiration-ms=86400000

# App credentials (single user)
app.auth.username=anjana
app.auth.password=1234

# CORS - update with your frontend URL when deployed
app.cors.allowed-origins=http://localhost:4200
